[package]
name = "hirushasuhan/frontend"
version = "0.1.7"
description = "UniAlloc Next.js Frontend for Wasmer Edge"

[dependencies]
"wasmer/static-web-server" = "^1.0.0"

[fs]
"/public" = "public"
"/settings" = "settings"

[[command]]
name = "run"
module = "wasmer/static-web-server:static-web-server"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-d", "/public", "-p", "80", "--page-fallback", "/public/index.html"]
env = [
  "PORT=80",
  "SERVER_PORT=80",
  "SERVER_ROOT=/public",
  "SERVER_PAGE_FALLBACK=/public/index.html"
]
